### ISSUE TITLE
CHANGELOG for v0.3.4 (and older) missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [lucasconstantino/graphql-resolvers#16]
I just saw the package is updated to `v0.3.4`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work @lucasconstantino! 🙂

**Comment by lucasconstantino** [comment]
Sorry @MichaelDeBoey, It's being a long time since I last worked on this project, but due to it's simplicity, the core part it's kind of still up-to-date with recent GraphQL usage.

The latest version is doesn't really follow semver, and I rolled this out mainly because of a fresh setup of QA (lint/test) tools I recently added, and also due to the automation of CHANGELOG.

I'll make sure to add this to the changelog but last breaking change there was is this PR: https://github.com/lucasconstantino/graphql-resolvers/pull/10. It does break only some edge cases though.

Sorry for the trouble.
