### ISSUE TITLE
Allow combineResolvers and pipeResolvers to reject

### ISSUE THREAD

**Issue by brandondoran** [lucasconstantino/graphql-resolvers#5]
First off, thanks for this very useful library.

The issue I'm running into is with how `combineResolvers` and `pipeResolvers` have a `.catch` that returns the error, rather than allowing the error to bubble up. This seems to be counter to how a regular resolver would work. 

Currently, as I user of the library, If I want to act on an error occurring in the resolver,  I have to use `instanceof` on the resolved value and if it's an `Error`, act appropriately.  If I want to allow graphql to just add the error to the `errors` array in the response, then I have to check with `instanceof` and if `Error` re-throw.

Perhaps I'm using it wrong, but I seems like it should be up to the code using the library to decide how error should be handled.

**Comment by lucasconstantino** [comment]
Basically I'm normalizing errors to returned values because of how the JavaScript GraphQL implementation works, which is, as far as I remember, to threat any throw errors as **resolving errors**, meaning they are actually returned on the query result, inside the `errors` prop.

For instance:

```js
  const typeDefs = `
    type Query {
      erroring: String!
    }

    schema {
      query: Query
    }
  `

  const resolvers = {
    Query: {
      erroring: () => { throw new Error('errored') }
    },
  }

  const schema = makeExecutableSchema({ typeDefs, resolvers })

  graphql(schema, '{ erroring }').then(result => {
    expect(result.errors[0].message).to.equal('Errored') // passes
  })
```

The above test passes. I see this can be misleading, though. And perhaps you are right, and my lib shouldn't interfere at all on throw errors - that would probably end up working exactly as it currently does, I guess.

Could you provide me with some code to contextualize on what you are trying to achieve?

**Comment by lucasconstantino** [comment]
I considered it again and I think you're right after all. Just published version 0.3.2 with this fixed ;)

**Comment by brandondoran** [comment]
Thanks for looking into so quickly! 🙇

**Comment by brandondoran** [comment]
@lucasconstantino would you be able to publish 0.3.2 to npm?

**Comment by lucasconstantino** [comment]
Sorry, @brandondoran. It is under a beta flag: `yarn add graphql-resolvers@beta`

**Comment by alanhr** [comment]
Hi @lucasconstantino.
Do you have any idea when you'll get the new release on npm ?

**Comment by lucasconstantino** [comment]
Sorry, sir. Done ;)
